export * from './create-ruta.interface';
export * from './get-rutas-paginated.interface';
export * from './get-ruta-by-zona-id.interface';
export * from './update-ruta.interface';
export * from './actived-ruta.interface';
export * from './get-rutas-activas.interface';
export * from './get-ruta-by-id.interface';
export * from './change-ruta.interface';
export * from './delete-ruta.interface';
